##################################################################
# Set electromagnetic model and interaction opitons
##################################################################

/SodiumIodideMC/physics/SetEmModel Standard
/SodiumIodideMC/physics/SetEmProcess All
/run/initialize

##################################################################
# Set input options
##################################################################

# /SodiumIodideMC/generator/Mode 1
# /SodiumIodideMC/generator/InputFile ~/data/Gen_SOURCE1.root

##################################################################
# Set output options
##################################################################

# /SodiumIodideMC/analysis/setOutputFile ~/data/Vis_SOURCE1.root

##################################################################
# Set visualisation options
##################################################################

#/vis/scene/create
#/vis/open OGLIX
#/vis/viewer/set/viewpointThetaPhi 70 20
#/vis/scene/add/trajectories
#/vis/modeling/trajectories/create/drawByCharge
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/select viewer-0
#/vis/viewer/rebuild

##################################################################

#/run/beamOn 50
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
# Use this open statement to create an OpenGL view:
/vis/open OGLSQt
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90. 90.
#/vis/viewer/set/viewpointThetaPhi 50. -95.
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/targetPoint 0. 0. 0.0 m
#/vis/viewer/set/targetPoint 0.0 -0.5 0.4 m
#
# Specify zoom value:
#/vis/viewer/zoom 5
/vis/viewer/zoom 1.1
#
#/vis/viewer/set/background white
# Specify style (surface or wireframe):
 /vis/viewer/set/style wireframe
#/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 1
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/setRGBA opticalphoton 0.2 0.6 0.2 1.0
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set neutron white
/vis/modeling/trajectories/drawByParticleID-0/set proton magenta
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set deuteron red
/vis/modeling/trajectories/drawByParticleID-0/set triton red
/vis/modeling/trajectories/drawByParticleID-0/set mu- yellow
/vis/modeling/trajectories/drawByParticleID-0/set mu+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/verbose warnings